FROM node:18.16.0
 
USER 0
 
RUN mkdir -p /home/node/whatsapp-util
WORKDIR /home/node/whatsapp-util

RUN apt-get update && apt install libssl-dev -y

RUN wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb && dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb 